name: Bundle and Deploy Frontend

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      near_wallet_env:
        required: true
        type: string

jobs:
  bundle-frontend:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: packages/frontend
    env:
      NEAR_WALLET_ENV: ${{ inputs.near_wallet_env }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9' 
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
      - run: yarn bundle --env $NEAR_WALLET_ENV
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Pulls Vercel token from GitHub secrets
        run: npx vercel --prod --token $VERCEL_TOKEN