name: Deploy Testnet

on:
  push:
    branches:
      - master

concurrency:
  group: 'near-wallet-master'
  cancel-in-progress: true

jobs:
  deploy-testnet:
    uses: ./.github/workflows/bundle-and-deploy.yml
    with:
      environment: testnet
      near_wallet_env: testnet_NEARORG
    secrets: inherit
